# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod download
builds:
- env:
  - CGO_ENABLED=0
- id: binary
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm
    - arm64
    - 386
  goarm:
    - 6
    - 7
  ldflags:
    - -a -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease
- id: snap
  goos:
    - linux
  goarch:
    - amd64
    - arm
    - arm64
    - 386
  goarm:
    - 6
    - 7
  ldflags:
    - -a -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=snap  
archives:
- builds:
    - binary
  replacements:
    linux: Linux
    windows: Windows
  format_overrides:
    - goos: windows
      format: zip    
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
